const MEGA_TYPES = {
  'Mega Venusaur': ['Planta', 'Veneno'],
  'Mega Charizard X': ['Fuego', 'Dragón'],
  'Mega Charizard Y': ['Fuego', 'Volador'],
  'Mega Blastoise': ['Agua'],
  'Mega Beedrill': ['Bicho', 'Veneno'],
  'Mega Pidgeot': ['Normal', 'Volador'],
  'Mega Raichu X': ['Eléctrico'],
  'Mega Raichu Y': ['Eléctrico'],
  'Mega Clefable': ['Hada', 'Volador'],
  'Mega Alakazam': ['Psíquico'],
  'Mega Victreebel': ['Planta', 'Veneno'],
  'Mega Slowbro': ['Agua', 'Psíquico'],
  'Mega Gengar': ['Fantasma', 'Veneno'],
  'Mega Kangaskhan': ['Normal'],
  'Mega Starmie': ['Agua', 'Psíquico'],
  'Mega Pinsir': ['Bicho', 'Volador'],
  'Mega Gyarados': ['Agua', 'Siniestro'],
  'Mega Aerodactyl': ['Roca', 'Volador'],
  'Mega Dragonite': ['Dragón', 'Volador'],
  'Mega Meganium': ['Planta', 'Hada'],
  'Mega Feraligatr': ['Agua', 'Dragón'],
  'Mega Ampharos': ['Eléctrico', 'Dragón'],
  'Mega Steelix': ['Acero', 'Tierra'],
  'Mega Scizor': ['Bicho', 'Acero'],
  'Mega Heracross': ['Bicho', 'Lucha'],
  'Mega Skarmory': ['Acero', 'Volador'],
  'Mega Houndoom': ['Siniestro', 'Fuego'],
  'Mega Tyranitar': ['Roca', 'Siniestro'],
  'Mega Sceptile': ['Planta', 'Dragón'],
  'Mega Blaziken': ['Fuego', 'Lucha'],
  'Mega Swampert': ['Agua', 'Tierra'],
  'Mega Gardevoir': ['Psíquico', 'Hada'],
  'Mega Sableye': ['Siniestro', 'Fantasma'],
  'Mega Mawile': ['Acero', 'Hada'],
  'Mega Aggron': ['Acero'],
  'Mega Medicham': ['Lucha', 'Psíquico'],
  'Mega Manectric': ['Eléctrico'],
  'Mega Sharpedo': ['Agua', 'Siniestro'],
  'Mega Camerupt': ['Fuego', 'Tierra'],
  'Mega Altaria': ['Dragón', 'Hada'],
  'Mega Banette': ['Fantasma'],
  'Mega Chimecho': ['Psíquico', 'Acero'],
  'Mega Absol': ['Siniestro'],
  'Mega Glalie': ['Hielo'],
  'Mega Metagross': ['Psíquico', 'Acero'],
  'Mega Staraptor': ['Lucha', 'Volador'],
  'Mega Lopunny': ['Normal', 'Lucha'],
  'Mega Garchomp': ['Dragón', 'Tierra'],
  'Mega Lucario': ['Lucha', 'Acero'],
  'Mega Abomasnow': ['Planta', 'Hielo'],
  'Mega Gallade': ['Psíquico', 'Lucha'],
  'Mega Froslass': ['Hielo', 'Fantasma'],
  'Mega Emboar': ['Fuego', 'Lucha'],
  'Mega Excadrill': ['Tierra', 'Acero'],
  'Mega Audino': ['Normal', 'Hada'],
  'Mega Scolipede': ['Veneno', 'Bicho'],
  'Mega Scrafty': ['Lucha', 'Siniestro'],
  'Mega Eelektross': ['Eléctrico'],
  'Mega Chandelure': ['Fantasma', 'Fuego'],
  'Mega Golurk': ['Tierra', 'Fantasma'],
  'Mega Chesnaught': ['Planta', 'Lucha'],
  'Mega Delphox': ['Fuego', 'Psíquico'],
  'Mega Greninja': ['Agua', 'Siniestro'],
  'Mega Pyroar': ['Normal', 'Fuego'],
  'Mega Floette': ['Hada'],
  'Mega Meowstic': ['Psíquico'],
  'Mega Malamar': ['Psíquico', 'Siniestro'],
  'Mega Barbaracle': ['Lucha', 'Roca'],
  'Mega Dragalge': ['Veneno', 'Dragón'],
  'Mega Hawlucha': ['Lucha', 'Volador'],
  'Mega Crabominable': ['Lucha', 'Hielo'],
  'Mega Drampa': ['Normal', 'Dragón'],
  'Mega Falinks': ['Lucha'],
  'Mega Scovillain': ['Planta', 'Fuego'],
  'Mega Glimmora': ['Roca', 'Veneno'],
  'Mega-Latias': ['Dragón', 'Psíquico'],
  'Mega-Latios': ['Dragón', 'Psíquico'],
  'Mega-Baxcalibur': ['Dragón', 'Hielo'],
  'Mega-Darkrai': ['Siniestro'],
  'Mega-Diancie': ['Roca', 'Hada'],
  'Mega-Garchomp Z': ['Dragón'],
  'Mega-Golisopod': ['Bicho', 'Acero'],
  'Mega-Heatran': ['Fuego', 'Acero'],
  'Mega-Lucario Z': ['Lucha', 'Acero'],
  'Mega-Magearna': ['Acero', 'Hada'],
  'Mega-Mewtwo X': ['Psíquico', 'Lucha'],
  'Mega-Mewtwo Y': ['Psíquico'],
  'Mega-Rayquaza': ['Dragón', 'Volador'],
  'Mega-Salamence': ['Dragón', 'Volador'],
  'Mega-Tatsugiri': ['Dragón', 'Agua'],
  'Mega-Zeraora': ['Eléctrico'],
  'Mega-Zygarde': ['Dragón', 'Tierra'],
  'Mega-Absol Z': ['Siniestro', 'Fantasma']
};

module.exports = { MEGA_TYPES };